name: liferea 
base: core18 
summary: Liferea is a desktop feed reader/news aggregator
license: GPL-2.0
description: |
  Liferea is a desktop feed reader/news aggregator that brings together all of
  the content from your favorite subscriptions into a simple interface that makes 
  it easy to organize and browse feeds. Its GUI is similar to a desktop mail/news 
  client, with an embedded web browser.

grade: stable
confinement: strict 
compression: lzo
adopt-info: liferea

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  liferea:
    slots:
    - dbus-liferea
    extensions: [gnome-3-28]
    desktop: usr/share/applications/net.sourceforge.liferea.desktop
    command: desktop-launch $SNAP/usr/bin/liferea
    environment: 
        XDG_DATA_DIR: $HOME
        GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
        GIT_CONFIG_NOSYSTEM: "true"
        GIT_EXEC_PATH: $SNAP/usr/lib/git-core
        GIT_TEXTDOMAINDIR: $SNAP/usr/share/locale
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
      - wayland 
      - desktop 
      - desktop-legacy #
      - opengl
  liferea-add-feed:
    slots:
    - dbus-liferea
    extensions: [gnome-3-28]
    command: usr/bin/liferea-add-feed
    environment:
        XDG_DATA_DIR: $HOME
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
      - wayland
      - desktop
      - desktop-legacy #


slots:
  dbus-liferea:
    interface: dbus
    bus: session
    name: net.sourceforge.liferea

layout:
  /usr/lib/liferea: 
    bind: $SNAP/usr/lib/liferea
  /usr/share/liferea: 
    bind: $SNAP/usr/share/liferea
  /usr/lib/x86_64-linux-gnu/libpeas-1.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/libpeas-1.0

parts:
  liferea:
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
      sed -i.bak -e 's|Icon=liferea|Icon=/usr/share/icons/hicolor/scalable/apps/liferea.svg|g' net.sourceforge.liferea.desktop.in
    source: https://github.com/lwindolf/liferea.git
    source-type: git
    plugin: autotools
    source-tag: v1.13.8
    override-build: |
      ./autogen.sh
      ./configure --prefix=/usr
      make
      ./configure --prefix=${SNAPCRAFT_PART_INSTALL}/usr
      make install
    stage-packages:
      - libpeas-1.0-0
      - python3-gi
      - git
      - python-gi
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libgstreamermm-1.0-1
      - gir1.2-secret-1
      - gir1.2-gstreamer-1.0
      - gir1.2-notify-0.7
      - python3-cairo
      - python3-gi-cairo
      - appmenu-gtk3-module
      - libcurl4-openssl-dev
      - libfribidi0
    build-packages:
      - intltool
      - flex
      - gettext
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libjson-glib-dev
      - libsqlite3-dev
      - libpeas-dev
      - libxslt1-dev
      - gsettings-desktop-schemas-dev
      - libgirepository1.0-dev
      - libfribidi-dev
