name: liferea 
base: core18 
version: 'v1.12.7'
summary: Liferea is a desktop feed reader/news aggregator
description: |
  Liferea is a desktop feed reader/news aggregator that brings together all of
  the content from your favorite subscriptions into a simple interface that makes 
  it easy to organize and browse feeds. Its GUI is similar to a desktop mail/news 
  client, with an embedded web browser.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict 

apps:
  liferea:
    slots:
    - dbus-liferea
    extensions: [gnome-3-28]
    desktop: usr/share/applications/net.sourceforge.liferea.desktop
    command: desktop-launch $SNAP/usr/bin/liferea
    environment: 
        XDG_DATA_DIR: $HOME
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
      - wayland 
      - desktop 
      - desktop-legacy #

slots:
  dbus-liferea:
    interface: dbus
    bus: session
    name: net.sourceforge.liferea


parts:
  liferea:
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|Icon=liferea|Icon=/usr/share/icons/hicolor/scalable/apps/liferea.svg|g' net.sourceforge.liferea.desktop.in
    source: https://github.com/lwindolf/liferea.git
    source-type: git
    plugin: autotools
    source-tag: v1.12.7
    override-build: |
      ./autogen.sh
      ./configure --prefix=/usr --datadir=/snap/liferea/current/usr/share/
      make
      ./configure --prefix=${SNAPCRAFT_PART_INSTALL}/usr
      make install

    build-packages:
      - intltool
      - flex
      - gettext
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libjson-glib-dev
      - libsqlite3-dev
      - libpeas-dev
      - libxslt1-dev
      - gsettings-desktop-schemas-dev
      - libgirepository1.0-dev
